BRANDS = [
    'scarpa',
    'la sportiva',
    'black diamond',
    'boreal',
    'butora',
    'evolv',
    'five ten',
    'mad rock',
    'ocun',
    'red chili'
    'tenaya',
    'unparallel'
]


SCARPA = [
    'mago',
    'boostic',
    'booster',
    'vapor v',
    'vapor',
    'vapor s',
    'veloce',
    'veloce lace',
    'reflex',
    'velocity',
    'reflex v',
    'drago',
    'drago lv',
    'chimera',
    'furia s',
    'furia air',
    'instinct vs',
    'instinct',
    'instinct sr',
    'instinct vsr',
    'arpia',
    'maestro eco',
    'maestro alpine',
    'maestro mid eco',
    'helix',
    'origin',
    'jungle',
    'force v',
    'generator mid',
    'generator',
    'quantix sf',
    'quantic',
]
LA_SPORTIVA = [
    'miura vs',
    'miura',
    'tc pro',
    'katana lace',
    'mantra',
    'skwama vegan',
    'tarantula boulder',
    'tarantula',
    'tarantulace',
    'aragon',
    'finale',
    'kubo',
    'mythos eco',
    'mythos',
    'cobra 4:99',
    'cobra eco',
    'skwama',
    'otaki',
    'solution comp',
    'solution',
    'theory',
    'futura',
    'genius',
    'testarossa',
    'mega ice evo',
    'python'
]

BLACK_DIAMOND = [
    'momentum',
    'momentum lace',
    'shadow',
    'shadow lv',
    'method',
    'method s',
    'aspect',
    'aspect pro'
]

BOREAL = [
    'synergy',
    'ace',
    'satori',
    'crux lace',
    'crux',
    'ninja',
    'diabolo',
    'diabola'
    'mutant',
    'beta eco',
    'beta',
    'dharma',
    'joker',
    'joker lace',
    'joker plus',
    'alpha',
    'silex'
]

BUTORA = [
    'gomi spinter',
    'acro comp',
    'altura',
    'mantra',
    'endeavor',
    'habara',
    'new bora',
    'brava'
]

EVOLV = [
    'defy lace',
    'defy',
    'eldo z',
    'elektra lace',
    'elektra',
    'geshido lace',
    'geshido',
    'kira',
    'kronos',
    'phantom',
    'phantom lv',
    'rave',
    'shaktra',
    'shaman',
    'shaman lace',
    'shaman lace lv',
    'shaman lv',
    'shaman pro',
    'shaman pro lv',
    'the general',
    'titan',
    'venga',
    'yosemite bum',
    'yosemite bum lv',
    'zenist',
    'zenist pro',
    'zenist pro lv'
]

FIVE_TEN = [
    'kirigami',
    'crawe',
    'niad lace',
    'niad moccasym',
    'niad vcs',
    'hiangle pro',
    'hiangle',
    'rogue vcs',
    'aleon',
    'quantum vcs',
    'asym',
    'anasazi',
]

MAD_ROCK = [
    'drone comp lv',
    'drone comp hv',
    'redline strap',
    'shark 2.0',
    'drone lv black',
    'drone hv black',
    'drone lv',
    'drone cs hv',
    'drone cs lv',
    'drone hv',
    'rover',
    'haywire',
    'lotus',
    'redline lace',
    'weaver',
    'remora',
    'remora lv',
    'remora hv',
    'remora tokyo',
    'm5',
    'lyra',
    'demon 2.0',
    'agama',
    'flash 2.0',
    'drifter',
    'pulse negative',
    'pulse positive',
    'badger',
   'phoenix'
]

OCUN = [
    'fury',
    'diamond',
    'ozone',
    'ozone hv',
    'bullit',
    'havoc',
    'jett qc',
    'jett lu',
    'jett crack',
    'pearl 20th anniversary',
    'advancer qc',
    'advancer lu',
    'striker lu',
    'striker qc',
    'rival',
    'rental',
    'ribbit'
]

RED_CHILI = [
    'sensor',
    'mystix',
    'voltage 2',
    'voltage lv',
    'voltage lace',
    'fusion',
    'fusion lv',
    'puzzle',
    'circuit lv',
    'circuit',
    'ventic air lace',
    'sausalito',
    'session 4 s',
    'session',
    'pulpo',
    'session air'
]

TENAYA = [
    'indalo',
    'mastia',
    'mundaka',
    'lati',
    'tarifa',
    'oasi',
    'oasi lv',
    'ra',
    'masai',
    'inti',
    'tatanka',
    'aqua+',
    'arai',
    'tanta',
    'tanta laces',
    'tanta lx'
]

UNPARALLEL = [
    'up pivot',
    'souped up',
    'engage lace up',
    'tn pro lv',
    'tn pro',
    'flagship lv',
    'flagship',
    'up-rise pro',
    'leopard 2',
    'up duel',
    'lyra',
    'regulus',
    'regulus lv',
    'vim',
    'sirius lace',
    'sirius lace lv',
    'newtro vcs',
    'up rise vcs',
    'up rise vcs lv',
    'up rise zero vcs lv',
    'up lace',
    'up lace lv',
    'engage vcs',
    'engage vcs lv',
    'newtro lace',
    'vega',
    'mocc',
    'grade mocc',
    'grade engage',
    'hold up slipper',
    'hold up vcs'
]


brandConstDict = {
    'scarpa': SCARPA,
    'la sportiva': LA_SPORTIVA,
    'black diamond':BLACK_DIAMOND,
    'boreal':BOREAL,
    'butora':BUTORA,
    'evolv':EVOLV,
    'five ten':FIVE_TEN,
    'mad rock':MAD_ROCK,
    'ocun':OCUN,
    'red chili':RED_CHILI,
    'tenaya':TENAYA,
    'unparallel':UNPARALLEL,
}
